### PR TITLE
fix: fixes vendoring issue

### LINKED ISSUE #21: vendoring this repository fails
I created a test repository that uses SIDH. The code compiles without any problems, until I vendor this repository. Then compilation fails with this error message
```
github.com/marten-seemann/sidh-test/vendor/github.com/cloudflare/sidh/p503.fp503Mul: relocation target github.com/cloudflare/sidh/internal/utils.HasADXandBMI2 not defined
github.com/marten-seemann/sidh-test/vendor/github.com/cloudflare/sidh/p503.fp503Mul: relocation target github.com/cloudflare/sidh/internal/utils.HasBMI2 not defined
github.com/marten-seemann/sidh-test/vendor/github.com/cloudflare/sidh/p503.fp503MontgomeryReduce: relocation target github.com/cloudflare/sidh/internal/utils.HasADXandBMI2 not defined
github.com/marten-seemann/sidh-test/vendor/github.com/cloudflare/sidh/p503.fp503MontgomeryReduce: relocation target github.com/cloudflare/sidh/internal/utils.HasBMI2 not defined
github.com/marten-seemann/sidh-test/vendor/github.com/cloudflare/sidh/p751.fp751MontgomeryReduce: relocation target github.com/cloudflare/sidh/internal/utils.HasADXandBMI2 not defined
github.com/marten-seemann/sidh-test/vendor/github.com/cloudflare/sidh/p751.fp751MontgomeryReduce: relocation target github.com/cloudflare/sidh/internal/utils.HasBMI2 not defined
```

### PR DESCRIPTION
**Pull request by henrydcase**
fix: fixes vendoring issue
    
    * Assembly code can't reffer to variables which are not in the
      same package.
    * utils/cpu.go keeps flags indicating CPU capabilities. Currently this
      file keeps flags specific to X86, those flags are set only if program
      is run on X86, hence on ARM they always be false. Flags are coppied
      to variables which are local to P503 and P751 (so that assembly code
      can access them).
    * we dont need workaround in utils/utils.go anymore as utils/cpu.go is
      never ignored by the buildtags.
    
    See also:
    https://github.com/golang/go/issues/28230
    
Fixes #21

### CODE REVIEW

**Comment by henrydcase** [comment]
@Ko- @marten-seemann  can you guys take a look?

File: p503/consts.go [hunk 1]
```diff
@@ -23,6 +24,17 @@ const (
 	NumWords = 8
 )
 
+// CPU Capabilities. Those flags are reffered by assembly code. According to
+// https://github.com/golang/go/issues/28230, variables reffered from the
```
Comment (Ko-) [inline p503/consts.go]: Typo: referred. (2x here + 2x in p751)

File: p503/arith_amd64_test.go [hunk 2]
```diff
@@ -21,21 +21,26 @@ const (
 	kUse_MULXandADxX = 1 << 2
 )
 
+func resetCpuFeatures() {
+	HasBMI2 = cpu.X86.HasBMI2
+	HasADXandBMI2 = cpu.X86.HasBMI2 && cpu.X86.HasADX
```
Comment (Ko-) [inline p503/arith_amd64_test.go]: It's still a shame that we need so many copies of these values...

Comment (henrydcase) [reply p503/arith_amd64_test.go]: It is. I don't understand why we can't refer from ASM to variables in different package. But because of that we need this dumb copy.

**Comment by henrydcase** [comment]
Thnx guys!
